### Create Response

POST https://api.openai.com/v1/responses
Authorization: Bearer {{OPEN_AI_API_KEY}}
Content-Type: application/json

{
  "model": "gpt-4.1-mini",
  "input": "What are some popular ways to cook chicken thighs?"
}

> {%
    client.global.set('response_id', response.body.id);
%}

### Use previous_response_id instead of passing entire context

POST https://api.openai.com/v1/responses
Authorization: Bearer {{OPEN_AI_API_KEY}}
Content-Type: application/json

{
  "previous_response_id": "{{response_id}}",
  "model": "gpt-4.1-mini",
  "input": "I only have a grill."
}


### Get Response

GET https://api.openai.com/v1/responses/{{response_id}}
Authorization: Bearer {{OPEN_AI_API_KEY}}
Content-Type: application/json

### Use web search tool

POST https://api.openai.com/v1/responses
Authorization: Bearer {{OPEN_AI_API_KEY}}
Content-Type: application/json

{
  "model": "gpt-4.1-mini",
  "input": "I am traveling to Boulder, CO tomorrow. Are there any events happening this next weekend?",
  "instructions": "Suggest clothing to pack for an upcoming trip. If you do not know the specifics for the weather forecast, do not provide an answer based on historical data.",
  "tools": [
    {
      "type": "web_search_preview"
    },
    {
      "type": "function",
      "name": "get_weather_forecast",
      "description": "Get tomorrow's weather forecast.",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "Location to get the weather forecast for."
          }
        },
        "required": [
          "location"
        ]
      }
    }
  ]
}