### Response with JSON Schema

POST https://api.openai.com/v1/responses
Authorization: Bearer {{OPEN_AI_API_KEY}}
Content-Type: application/json

{
  "model": "gpt-4.1-mini",
  "input": "What are some good bakeries near 3100 Carbon Pl in Boulder, CO?",
  "text": {
    "format": {
      "type": "json_schema",
      "name": "bakery_schema",
      "strict": true,
      "description": "Information about a bakery",
      "schema": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the bakery"
          },
          "address": {
            "type": "string",
            "description": "Address of the bakery"
          }
        },
        "required": [
          "name",
          "address"
        ],
        "additionalProperties": false
      }
    }
  }
}
